// busybox libraries configuration
#define ENABLE_DEBUG 0
#define ENABLE_FEATURE_CLEAN_UP 0
#define O_ACCMODE 0
#define BB_VER 1
#define ENABLE_SHA512SUM 0
#define ENABLE_USE_BB_CRYPT_SHA 0
#define CONFIG_SHA3_SMALL 0
#define ENABLE_SHOW_USAGE 0
#define NUM_APPLETS 0
#define ENABLE_LOCALE_SUPPORT 0
#define CONFIG_FEATURE_COPYBUF_KB 0
#define ENABLE_FEATURE_USE_SENDFILE 0
#define ENABLE_FEATURE_PREFER_APPLETS 0

// vi.c configuration
#define CONFIG_FEATURE_VI_MAX_LEN 4096
#define ENABLE_FEATURE_VI_COLON 1
#define ENABLE_FEATURE_VI_ASK_TERMINAL 1
#define ENABLE_FEATURE_LESS_ASK_TERMINAL 1
#define ENABLE_FEATURE_VI_DOT_CMD 1
#define ENABLE_FEATURE_VI_SET 1
#define ENABLE_FEATURE_VI_CRASHME 0
// must be off for now
#define ENABLE_FEATURE_VI_READONLY 0
#define ENABLE_FEATURE_VI_YANKMARK 0
#define ENABLE_FEATURE_VI_USE_SIGNALS 0
#define ENABLE_FEATURE_VI_WIN_RESIZE 0
#define ENABLE_FEATURE_EDITING_ASK_TERMINAL 0
